### ISSUE TITLE
Source for documentation

### ISSUE THREAD

**Issue by NavidMitchell** [mtorromeo/vue-patternfly3#13]
Hello, 

Thank you for the great work. I really like patternfly and I am very happy to see a vue implementation. 

Would it be possible for you to publish the source for your documentation site? This would be a helpful reference when getting started with vue-patternfly.

**Comment by Dhallagan** [comment]
Hi @NavidMitchell,
It isn't obvious, but it is in a different branch:
https://github.com/mtorromeo/vue-patternfly/tree/gh-pages

**Comment by NavidMitchell** [comment]
Awesome! Thank you for getting back to me so quickly. :)
