### ISSUE TITLE
Patterfly Next Support

### ISSUE THREAD

**Issue by williamjmorenor** [mtorromeo/vue-patternfly3#14]
Hello and good job putting together Patternfly and Vue, this projects follows the original patternfly project:

https://github.com/mtorromeo/vue-patternfly/blob/master/yarn.lock#L5311

Do you have any plans to support Patternfly-next?

https://github.com/patternfly/patternfly-next

**Comment by mtorromeo** [comment]
Hi,
I've been loosely following the development of patternfly-next and I'm certainly interested in supporting it but this will probably be developed into a separate library.

I haven't really decided anything yet and it's still early to start working on it since patternfly-next is still under heavy development and nothing has stabilized yet.

**Comment by maltegrosse** [comment]
seems patternfly 4 stable is out now. any plans yet to support the next version?

**Comment by mtorromeo** [comment]
I have mixed feelings about patternfly 4. I like how the code has been reorganized and some of the new elements but I am not crazy about the use of space and the overly flat design that sometimes makes it difficult to easily identify widgets or to recognize the separation between the elements.

That being said I need to work on applications designed with patterfly 4 and so I will definitely make a pf4 compatible version of vue-patternfly. I still have to decide whether to just bump the major version or if it would be better to work on a separate project.

**Comment by mtorromeo** [comment]
Took me a while, but I published a WIP package for PatternFly 4 and Vue 3: https://mtorromeo.github.io/vue-patternfly4/

More components are implemented than what are present in the storybook, and I am in the process of adding a story for each component in the coming days.

**Comment by 0x0dr1y** [comment]
@mtorromeo Glad that you‘re working on pf4! Are there any plans to make it kind of „backward  compatible“ with this Version?

**Comment by mtorromeo** [comment]
No, sorry.
The 2 designs are too different and a lot of components do not match up at all. On top of that, I moved on to Vue 3 and that adds another layer of complexity to have any kind of compatibility.

Maybe it would be possible to develop a set of "wrappers" that use the new components to implement something that works like the patternfly 3 components, but it would still require migrating to Vue 3.

I don't think it is worth the effort (and I lack the time anyway)

**Comment by mtorromeo** [comment]
I gave it some thought more, and I decided to do a last update to this version of the library to port it to Vue 3.
This will help transition the app to Vue 3 first and then to vue-patternfly4 in separate steps. The amount of work required is relatively small, but there will obviously be some breaking changes.
