### ISSUE TITLE
 [PfFilterFields]: Cannot create property 'dropdown' on boolean 'true'

### ISSUE THREAD

**Issue by pebri86** [mtorromeo/vue-patternfly3#15]
I using PfToolbar components and faced an issue above and cannot find a solution, the problem also occured on PfSort as well, 

tested with Vue 2.6.6.
thanks

**Comment by pebri86** [comment]
I'm sorry i accidentally bumped vue version to 2.6.8, with vue 2.6.6 it works perfectly.
thanks, i'll close the issue.

**Comment by mtorromeo** [comment]
I'll have to take a look at what's the issue with 2.6.8

**Comment by mtorromeo** [comment]
This is now fixed in 0.0.23 by f0a50915e418a9175f10fab76ba8e10e6ce79217

**Comment by pebri86** [comment]
Great! i'll test with latest version. 

thanks.
