### ISSUE TITLE
pf-dropdown close not working in modal

### ISSUE THREAD

**Issue by maltegrosse** [mtorromeo/vue-patternfly3#17]
Hello,

seems like to automatically close functionality doesnt work when the pf select is used in a modal.
I personally use it in the toolbar component within a modal.
Perhaps its related to the z-index.. i couldnt figure it out. I can also see that no close event is fired by choosing an item. (PfDropDown $emit, input false).
![drop-down-close](https://user-images.githubusercontent.com/16973405/67263532-b03d4800-f4a8-11e9-9212-83a2c8cd832a.PNG)

**Comment by mtorromeo** [comment]
It's probably due to the fact that the dropdown relies on the click event on `window` to detect a click outside of itself and the modal component prevents clicks to reach `window` because it also uses the same logic.

**Comment by maltegrosse** [comment]
yes, but the outside click isnt my big issue. I prefer once after choosing an item the drop down should be hidden. It works by clicking the drop down arrow

**Comment by mtorromeo** [comment]
I understand, the issue is that even the click on a dropdown item must bubble up to the window object for the dropdown to close. This behavior is inherited from the uiv dropdown. I'll work on a solution.
