### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by maltegrosse** [mtorromeo/vue-patternfly3#19]
Moderate        Cross-Site Scripting                                          
                                                                                
  Package         jquery                                                        
                                                                                
  Patched in      >=3.5.0                                                       
                                                                                
  Dependency of   vue-patternfly                                                
                                                                                
  Path            vue-patternfly > patternfly > jquery                          
                                                                                
  More info       https://npmjs.com/advisories/1518                             
                                                                                
                                                                                
  High            Cross-Site Scripting                                          
                                                                                
  Package         bootstrap-select                                              
                                                                                
  Patched in      >=1.13.6                                                      
                                                                                
  Dependency of   vue-patternfly                                                
                                                                                
  Path            vue-patternfly > patternfly > bootstrap-select                
                                                                                
  More info       https://npmjs.com/advisories/1522

**Comment by mtorromeo** [comment]
Thanks for the report but it must be noted that jquery is not used in vue-patternfly so unless you are including it by hand in you project, it's just an inert file on disk.

**Comment by maltegrosse** [comment]
oh  sorry, my mistake - somehow happend in my dev env.
