### ISSUE TITLE
Tooltip directive implementation is not documented

### ISSUE THREAD

**Issue by ctaleck** [mtorromeo/vue-patternfly3#3]
I would like to use a tooltip in my project, but I see vue-strap's tooltip implementation has been dropped in favor of a directive based on [tether-tooltip](https://www.npmjs.com/package/tether-tooltip). I am unable to get it to work and was wondering if someone could post a working example.

**Comment by mtorromeo** [comment]
Documentation added: https://mtorromeo.github.io/vue-patternfly/#/tooltips
