### ISSUE TITLE
Secondary and tertiary nav items

### ISSUE THREAD

**Issue by Juli-FlowD** [mtorromeo/vue-patternfly3#4]
Hi! 

First of all thank you, for your work! 
I have an issue with the secondary nav. I have implemented it in the vertical-menu slot with the pf-layout like this:

    <template slot="vertical-menu">
      <li class="list-group-item active secondary-nav-item-pf is-hover" data-target="#ipsum-secondary">
        <a>
          <span class="fa fa-space-shuttle" data-toggle="tooltip" title="Ipsum"></span>
          <span class="list-group-item-value">Ipsum</span>
        </a>
        <div id="ipsum-secondary" class="nav-pf-secondary-nav">
          <div class="nav-item-pf-header">
            <a class="secondary-collapse-toggle-pf" data-toggle="collapse-secondary-nav"></a>
            <span>Ipsum</span>
          </div>
          <ul class="list-group">
            <li class="list-group-item active " data-target="#ipsum-intellegam-tertiary">
              <a>
                <span class="list-group-item-value">Intellegam</span>
              </a>
            </li>
            <li class="list-group-item " data-target="#ipsum-copiosae-tertiary">
              <a>
                <span class="list-group-item-value">Copiosae</span>
              </a>
            </li>
            <li class="list-group-item " data-target="#ipsum-patrioque-tertiary">
              <a>
                <span class="list-group-item-value">Patrioque</span>
              </a>
            </li>
          </ul>
        </div>
      </li>
    </template>

This is just copy and paste from the original Patternfly website. The vertical menu shows the Ipsum element as expected, but the secondary nav does not show up. It appears in the code as it should be and by hovering over the secondary nav div container in my web inspector, the element is marked but not shown. 

Sorry if this is not the right place for my problem, but I've been stuck with this simple implementation for days. Thanks for any help!

**Comment by mtorromeo** [comment]
This is something that I planned on testing but did not get to that point yet.
I suspected it wouldn't work as anything that requires javascript in the official jQuery based implementation, will need to be addressed with some Vue code.
I will take a look at this.

**Comment by iitsoftware** [comment]
The sub menus are displayed via tooltip toggles. Since this is a opt-in functionality in bootstrap, they must be enabled by jQuery. I tried everything to enable it but always getting "tooltip is not a function". 

Here is my take in the [Vue Forum](https://forum.vuejs.org/t/enabling-bootstrap-tooltip-with-jquery-in-a-vuejs-component/18212).

The problem is that we need these sub menus and that we use patternfly. If it turns out that it doesn't work at all, we have to drop pattern fly from our project,
