### ISSUE TITLE
Rows doesn'ts display

### ISSUE THREAD

**Issue by martuico** [mtorromeo/vue-patternfly3#5]
Here's the pf-table component 
![image](https://user-images.githubusercontent.com/2949921/31143100-cd917e8c-a8ae-11e7-85f7-22ac2ac5794c.png)

Here's vue component script.
![image](https://user-images.githubusercontent.com/2949921/31143133-df5bd338-a8ae-11e7-9aad-423865878ff3.png)

![image](https://user-images.githubusercontent.com/2949921/31142960-666471c4-a8ae-11e7-84c7-7cd21499758e.png)

**Comment by mtorromeo** [comment]
Hi,
I can't tell what is inside `res['users'].data` in your code.

Can you provide a sample data set?

**Comment by martuico** [comment]
ahh it is now working. I just a added template component and put the scope in it. but the sortable on columns doesn't work.
