### ISSUE TITLE
Sort not working

### ISSUE THREAD

**Issue by martuico** [mtorromeo/vue-patternfly3#6]
<pf-table
                    :columns="columns"
                    :rows="rows"
                    :page.sync="page"
                    :pages="pages"
                    :striped="true"
                    :bordered="true"
                    :hover="true"
                    :selectable="true"
                    :sortable="true"
                    :scrollable="true"
                    :sort-by.sync="sortBy"
                    :sort-direction.sync="sortDirection"
                >
                          <template scope="data">
                            <td>{{ data.row.username }}</td>
                            <td>{{ data.row.email }}</td>
                            <td>{{ isActive(data.row) }}</td>
                            <td>
                                <span v-for="role in data.row.roles" class="label label-default">{{role.name}}</span>
                            </td>
                        </template>
                    <template slot="action" scope="data">
                        <ul class="list-inline actions-cust">
                            <li><a class="btn btn-info btn-xs"><i class="fa fa-eye"></i></a></li>
                            <li><a class="btn btn-info btn-xs"><i class="fa fa-edit"></i></a></li>
                        </ul>
                    </template>
                </pf-table>
`data() {
            return {
                rows: [],
                page: 0,
                pages: 0,
                attached:true,
                columns: [
                "username",
                "email",
                "status",
                ""
                ],
                showColumn: [
                    "username",
                    "email",
                    "status",
                    ""
                ],
                sortFields: {
                    "username": "Username",
                    "email": "Email",
                    "is_active": "Status"
                },
                filters: [],
                filterFields: {
                    "username": {
                        "label": "Username"
                    },
                    "email": {
                        "label": "Email"
                    }
                },
                pickedColumns: ['Username'],
                resultCount: 0,
                sortBy: '',
                sortDirection: ''
            }
        },
        mounted() {
            let self = this;
            $.ajax({
                url: ApiRoutes.paths.UsersManagement,
                type: 'get',
                success: function(res) {
                    self.rows = res['users'].data;
                    self.page = res['users'].current_page;
                    self.pages = res['users'].last_page;
                },
                errors: function(res){
                    console.log(res);
                }
            });
        },
        methods: {
            isActive: function(item){
                return item.is_active ? 'Active':'Suspended';
            }
        }
`
I've check the source there's setSortBy method but dunno why its not working

**Comment by mtorromeo** [comment]
The `pf-table` component doesn't do sorting. It just provides the necessary UI controls.

There are multiple reasons behind this:
1. the actual sorting might be something more complex than a simple string comparison.
2. you might be receiving the data from a backend which does the sorting for you through an API.
3. if the number of rows is high enough that the data needs to be paged, you don't want to sort just the first page of data but you have to sort it in the backend (like in point 2).

Doing a simple javascript sort should be simple enough anyway. I suggest the use of a computed property which returns the rows sorted by the selected field.
