### ISSUE TITLE
EmptyChart

### ISSUE THREAD

**Issue by MikeDepies** [mtorromeo/vue-patternfly3#7]
The property, height, is not being applied to the actual dom. It appears that Vue requires px at the end.
<div class="empty-chart-content" :style="{
    'height': height + 'px',
    'padding-top': padding,
  }">

The same would be true for padding it seems. When I inspect the virtual Dom, the height property is set correctly. I suspect this issue is rampant across this repo.

**Comment by mtorromeo** [comment]
Yes, the charts are the oldest components that I implemented and soon left behind prioritising other components. All the other components are in a better state and have also basic documentation.

I do intend to improve them and properly document them though.

**Comment by MikeDepies** [comment]
I'd like to contribute to the project, but am having trouble building the node project (I've tried both on a windows machine and a linux machine)

**Comment by mtorromeo** [comment]
This was fixed in 65eb66de4
