### ISSUE TITLE
Unable to install and build

### ISSUE THREAD

**Issue by MikeDepies** [mtorromeo/vue-patternfly3#8]
"running npm install && npm run prepublish" fails to execute and build properly.

**Comment by mtorromeo** [comment]
I need more details on what fails and/or what do you intend with "properly".

**Comment by MikeDepies** [comment]
[npm-debug.log](https://github.com/mtorromeo/vue-patternfly/files/1593643/npm-debug.log)

**Comment by MikeDepies** [comment]
...
8728 verbose lifecycle vue-patternfly@0.0.13~prepublish: CWD: /home/michael/Documents/Development/vue-patternfly
8729 silly lifecycle vue-patternfly@0.0.13~prepublish: Args: [ '-c', 'npm run lint && npm run build' ]
8730 silly lifecycle vue-patternfly@0.0.13~prepublish: Returned: code: 1  signal: null
8731 info lifecycle vue-patternfly@0.0.13~prepublish: Failed to exec prepublish script
8732 verbose stack Error: vue-patternfly@0.0.13 prepublish: `npm run lint && npm run build`
8732 verbose stack Exit status 1
8732 verbose stack     at EventEmitter.<anonymous> (/home/michael/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/utils/lifecycle.js:233:16)
8732 verbose stack     at emitTwo (events.js:87:13)
8732 verbose stack     at EventEmitter.emit (events.js:172:7)
8732 verbose stack     at ChildProcess.<anonymous> (/home/michael/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
8732 verbose stack     at emitTwo (events.js:87:13)
8732 verbose stack     at ChildProcess.emit (events.js:172:7)
8732 verbose stack     at maybeClose (internal/child_process.js:818:16)
8732 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
8733 verbose pkgid vue-patternfly@0.0.13
8734 verbose cwd /home/michael/Documents/Development/vue-patternfly
8735 error Linux 4.10.0-28-generic
8736 error argv "/home/michael/.nvm/versions/node/v5.0.0/bin/node" "/home/michael/.nvm/versions/node/v5.0.0/bin/npm" "install"
8737 error node v5.0.0
8738 error npm  v3.3.6
8739 error code ELIFECYCLE
8740 error vue-patternfly@0.0.13 prepublish: `npm run lint && npm run build`
8740 error Exit status 1
8741 error Failed at the vue-patternfly@0.0.13 prepublish script 'npm run lint && npm run build'.
8741 error This is most likely a problem with the vue-patternfly package,
8741 error not with npm itself.
8741 error Tell the author that this fails on your system:
8741 error     npm run lint && npm run build
8741 error You can get their info via:
8741 error     npm owner ls vue-patternfly
8741 error There is likely additional logging output above.
8742 verbose exit [ 1, true ]

**Comment by mtorromeo** [comment]
Can you try skipping the linter and just use `npm run build`?

That should be enough for development. Also you might prefer using `npm run dev` while working on the code to enable the webpack watcher which auto rebuilds the code on change.

**Comment by MikeDepies** [comment]
Same(ish) issue. This is a fresh clone of your repo.
NPM version: 3.3.6
Node Version: 5.0.0

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/home/michael/.nvm/versions/node/v5.0.0/bin/node',
> 1 verbose cli   '/home/michael/.nvm/versions/node/v5.0.0/bin/npm',
> 1 verbose cli   'run',
> 1 verbose cli   'build' ]
> 2 info using npm@3.3.6
> 3 info using node@v5.0.0
> 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
> 5 info lifecycle vue-patternfly@0.0.13~prebuild: vue-patternfly@0.0.13
> 6 silly lifecycle vue-patternfly@0.0.13~prebuild: no script for prebuild, continuing
> 7 info lifecycle vue-patternfly@0.0.13~build: vue-patternfly@0.0.13
> 8 verbose lifecycle vue-patternfly@0.0.13~build: unsafe-perm in lifecycle true
> 9 verbose lifecycle vue-patternfly@0.0.13~build: PATH: /home/michael/.nvm/versions/node/v5.0.0/lib/node_modules/npm/bin/node-gyp-bin:/home/michael/Documents/Development/vue-patternfly/node_modules/.bin:/home/michael/.nvm/versions/node/v5.0.0/bin:/home/michael/bin:/home/michael/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> 10 verbose lifecycle vue-patternfly@0.0.13~build: CWD: /home/michael/Documents/Development/vue-patternfly
> 11 silly lifecycle vue-patternfly@0.0.13~build: Args: [ '-c', 'npm run purge && npm run compile' ]
> 12 silly lifecycle vue-patternfly@0.0.13~build: Returned: code: 1  signal: null
> 13 info lifecycle vue-patternfly@0.0.13~build: Failed to exec build script
> 14 verbose stack Error: vue-patternfly@0.0.13 build: `npm run purge && npm run compile`
> 14 verbose stack Exit status 1
> 14 verbose stack     at EventEmitter.<anonymous> (/home/michael/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/utils/lifecycle.js:233:16)
> 14 verbose stack     at emitTwo (events.js:87:13)
> 14 verbose stack     at EventEmitter.emit (events.js:172:7)
> 14 verbose stack     at ChildProcess.<anonymous> (/home/michael/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
> 14 verbose stack     at emitTwo (events.js:87:13)
> 14 verbose stack     at ChildProcess.emit (events.js:172:7)
> 14 verbose stack     at maybeClose (internal/child_process.js:818:16)
> 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> 15 verbose pkgid vue-patternfly@0.0.13
> 16 verbose cwd /home/michael/Documents/Development/vue-patternfly
> 17 error Linux 4.10.0-28-generic
> 18 error argv "/home/michael/.nvm/versions/node/v5.0.0/bin/node" "/home/michael/.nvm/versions/node/v5.0.0/bin/npm" "run" "build"
> 19 error node v5.0.0
> 20 error npm  v3.3.6
> 21 error code ELIFECYCLE
> 22 error vue-patternfly@0.0.13 build: `npm run purge && npm run compile`
> 22 error Exit status 1
> 23 error Failed at the vue-patternfly@0.0.13 build script 'npm run purge && npm run compile'.
> 23 error This is most likely a problem with the vue-patternfly package,
> 23 error not with npm itself.
> 23 error Tell the author that this fails on your system:
> 23 error     npm run purge && npm run compile
> 23 error You can get their info via:
> 23 error     npm owner ls vue-patternfly
> 23 error There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

**Comment by mtorromeo** [comment]
Ok, can you try separately running `npm run purge` and `npm run compile` and see if they both fail?

**Comment by MikeDepies** [comment]
npm run compile is the culprit

**Comment by mtorromeo** [comment]
You should be able to run webpack directly with `node_modules/.bin/webpack -p`. What output do you get?

**Comment by MikeDepies** [comment]
Oh so my linux vm was running on node 5.0... Updating that has allowed me to get the project to build properly. Still haven't been able to get webpack to play nice on with this project on my windows machine. But webpack does seem to work fine in another project (generated by the vue-cli tool)

**Comment by mtorromeo** [comment]
I was getting to that conclusion as well even though the npm logs only reported useless informations and never the actual errors. I'll add a minimum node version requirement to the package.json.
To what node version did you upgrade?

**Comment by MikeDepies** [comment]
I upgrade to 9.3 thought I think I came across something that said it "wanted" 6.0. I haven't figured out the window's woes yet, but will mess around a bit more on that end since it's my default development environment.

**Comment by MikeDepies** [comment]
Asset    Size  Chunks             Chunk Names
vue-patternfly.js  245 kB       0  [emitted]  vue-patternfly
   [4] (webpack)/buildin/harmony-module.js 648 bytes {0} [built]
  [61] (webpack)/buildin/amd-options.js 82 bytes {0} [built]
  [81] (webpack)/buildin/global.js 589 bytes {0} [built]
  [91] ./src/index.js + 169 modules 281 kB {0} [built]
 [127] ./src/index.css 5.54 kB {0} [built] [failed] [1 error]
 [243] ./node_modules/tether/dist/js 160 bytes {0} [built]
 [244] ./node_modules/css-loader!./src/index.css 5.69 kB [built]
    + 240 hidden modules

for what ever reason I'm unable to get the css file to build with webpack while on a windows machine. Any ideas?

**Comment by mtorromeo** [comment]
Sorry, no idea.
You might want to try the "Windows Subsystem for Linux" [1] as an alternative to running a virtual machine. I didn't try it myself but that's what I would do if I had to use Windows.

[1] https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by MikeDepies** [comment]
I got webpack to finally work with the project on windows 10. The modules=false in babelrc file was causing it to fail. I removed the property(defaulted to commonjs) and it builds perfectly. The only other issue I found was with the lint config expecting Unix line breaks.
