### ISSUE TITLE
[Vue warn]: The computed property "fields" is already defined as a prop.

### ISSUE THREAD

**Issue by martuico** [mtorromeo/vue-patternfly3#9]
![image](https://user-images.githubusercontent.com/2949921/34453310-4072e1f8-ed8c-11e7-95c9-eba7f82654af.png)

**Comment by mtorromeo** [comment]
There is something strange going on here because there's no computed property named `fields` in this library. Did you define it yourself? Are you using master or a tagged release?

**Comment by martuico** [comment]
I just follow your instruction npm install --save vue-patternfly

**Comment by mtorromeo** [comment]
I need a reproducible example to fix this. I don't really think this is a bug but probably invalid usage.
